export enum InventoryMovementHeaderType {
  PURCHASE_RECEIPT = 'purchase_receipt',
  SALES_DISPATCH = 'sales_dispatch',
  SALES_ALLOCATED = 'sales_allocated',
  STOCK_ADJUSTMENT = 'stock_adjustment',
  TRANSFER = 'transfer',
  MANUAL_CORRECTION = 'manual_correction',
  RESERVATION = 'reservation',
  RELEASE = 'release',
  RETURN_IN = 'return_in',
  RETURN_OUT = 'return_out',
  PURCHASE_EXPECTED = 'purchase_expected',
  DISPATCH_CANCELLED = 'dispatch_cancelled',
  DISPATCH_RETURN = 'dispatch_return',
}
